add missing "-"
as a note, `ipfs pin ls -type=all` shows that argument parsing is trimming args wrong, need to check.

```bash
» ipfs pin ls -type=all                                                    
Error: Invalid type 'ype=all', must be one of {direct, indirect, recursive, all}
Use 'ipfs pin ls --help' for information about this command
```